[package]
name = "spiders-widget"
version = "0.0.0"
edition = "2021"
authors = ["Cuprum Wangzuo <cuprumwz@foxmail.com>"]
description = "Spiders leptos widget"
license = "MIT OR Apache-2.0"


[dependencies]
