[package]
name = "spiders-bailor"
version = "0.0.0"
edition = "2021"
authors = ["Cuprum Wangzuo <cuprumwz@foxmail.com>"]
description = "Spiders tonic proxy"
license = "MIT OR Apache-2.0"


[dependencies]
